---
bibliography: bib/thesis.bib
---

# Conclusion {.unnumbered}

Inequality has historically been associated with increased risk-taking behaviours [@mishra2015; @payne2017; @krupp2018]. This project has likewise established a link between inequality and a unique case of risk aversion - social distrust. Under conditions of income inequality, individuals are more willing to pay for security products that reduce the likelihood of their partner successfully attacking them. Moreover, mediation analyses established that the effect of inequality was mediated through anticipated partner envy - a relationship that has not yet been predicted under theories of inequality and distrust. The effect of inequality was also surprisingly robust to conditions of fairness; when an unequal distribution was deserved, participants consumed a statistically equivalent amount of security goods compared to when disparities were determined randomly. Lastly, the relationship between inequality and security consumption was observed using archival data, although this relationship was not robust across different years of analysis. Taken as a whole, this project provides evidence with both high internal and external validity that inequality is indeed linked to the consumption of security products. However, this effect is not without its limitations and caveats.

This project most directly builds on a growing body of empirical and theoretical work examining how the expectation of envy impacts people's distrustful thoughts, feelings, and behaviours. Previous studies have established that people are fearful of others' envious reactions [@juola-exline1997; @horner1968; @ishiyama1984], as well as this fear leading to increased helping behaviours [@vandeven2010]. This project makes a unique contribution by demonstrating that people are willing to incur tangible monetary costs to protect themselves from others' envious reactions. The experiments likewise went beyond other tests of envy anticipation by explicitly controlling for payoff motivations, which helps to rule out the role of advantageous inequity aversion. @vandeven2010 attempted to control for a sense of sympathy by introducing a condition where helping behaviours were directed toward a third disadvantaged person outside of the initial dyad, who did not know that the participant was better-off (in effect attempting to manipulate income visibility). However, the introduction of this third person confounded group membership with income visibility. Individuals are known to quickly apply norms to guide preferential treatment within groups [@tajfel1971], so a lack of helping behaviours towards a third party may not be due to a lack of envy anticipation, but rather a lack of sympathy or sense of obligation towards a person outside of the initial group. In this project, statistically controlling for payoff motivations and solely manipulating income visibility generally provided cleaner tests of the envy anticipation model. In addition, the effect of inequality on security consumption was tested using archival data on real-world inequality and individual security behaviours.

One notable limitation across the experiments in Chapters One and Two is that participants are always better-off in the high-inequality conditions. This relative advantage introduces a potential confound in the effect of inequality; are people wary of those who are worse-off, or are those who are better-off wary of other people? This question almost sounds redundant, but becomes important when trying to apply the theory of envy anticipation to groups larger than two people. For instance, individuals who are better-off may become less trusting of others, not because of their anticipation of envy, but rather due to their efforts to maintain their current standing in the group. Under this assumption, better-off individuals may be less trusting of all other partners - even those who share similar standing. By contrast, the posited model of envy anticipation predicts that people distrust those who are worse off.

<!-- To many, inequality is a corrosive force that gnaws at the roots of society, forcing individuals into conflict in a scramble to avoid falling behind. -->

<!-- @san-juan2012 -->

<!-- According to [@dolan2007], fear of crime is, above all, a reason to be concerned about people's self-protective and avoidance measures in response to it, which can have a significant impact -->

<!-- ## Theoretical developments -->

<!-- How do people come to distrust? -->

<!-- Is there a parallel/gap in how people experience envy vs. how people EXPECT others to experience envy? -->

<!-- Does charitable giving reduce security consumption? -->

<!-- Does reciprocity reduce security consumption? -->

<!-- Does security consumption happen through hierarchy maintenance? (i.e., ) -->

<!-- Does locality of competition moderate the effect of inequality? -->

<!-- Does inequality in competitive ability strengthen the effect of inequality on security consumption? -->

<!-- Is envy anticipation just an artifact of being better off? -->

<!-- ## Practical applications -->

The presence of the envy anticipation effect across both small-scale experiments and macro-level archival data raises some interesting questions for how inequality affects trust for different types of groups. For instance, a potential implication of this research is in the workplace. Employees can regularly have the chance to harm co-workers in order to benefit themselves (e.g., gossip, taking credit for work, ostracizing, theft). These results suggest that inequality within the workplace may serve to undermine trust, as individuals seek to insulate themselves from potentially harmful behaviours (e.g., communicating less, not sharing resources), and consequently undermining individual and group-level productivity. Given that nearly all workplaces have some degree of stratification, such as a supervisor being paid more, it is worth considering how social comparisons may cascade into lower trust. In general, inequality should be most likely to produce lower trust under the same conditions as when inequality will produce experiences of envy and relative deprivation. The effect of inequality will be stronger when individuals are judged to be similar on some dimension [@hazlewood1986]. Likewise, greater reductions in trust will occur when individuals are likely to compete with each other at later points [@krupp2018].

Beyond the workplace, the effects of inequality on security behaviours in a consumer context should generally be strongest at smaller scales. In this respect, the examination of country-level inequality in Chapter 3 might serve as a conservative test of how inequality affects individual decision-making. The trust-eroding effects of inequality might be stronger (and easier to detect) at more "meso" levels of comparison, such as cities or neighborhoods. For instance, Canada may have an intermediate to low level of inequality compared to other countries, but this "macro" picture of income distribution is an imperfect reflection of whether inequality is present and noticeable in a person's day-to-day life. For instance, as a city, Vancouver is likely to be more unequal than St. John's. Likewise, some neighborhoods in these cities will have more or less disparity, such as those areas experiencing gentrification. Depending on one's lifestyle, the relative income of someone in another city or province is unlikely to have a large impact on one's psychology and consumption. By contrast, regularly seeing a large disparity between the "haves" and "have-nots" in one's daily life may come to change one's overall (dis)trust in other people.

In the managerial context, the results in this project suggest that practitioners in the security industry may stand to profit by targeting countries, cities, and neighborhoods that are higher in inequality for their marketing strategies. This suggestion may provide a unique contribution, even beyond the link between inequality and crime. Many areas may be high in inequality, yet low in crime. Nonetheless, individuals may become more fearful of crime, because they anticipate the strain of envy amongst their neighbors and peers.

Importantly, the link between inequality and security consumption may have direct impacts on societal and organizational pursuits towards equity, diversity, and inclusion. The consumption of security products can be an exclusionary practice. Individuals pay sizable prices to live in a gated community precisely because it offers control over who can enter. This control of space and resources designates certain individuals and groups as unwelcome and threatening. As such, security consumption can serve to fortify existing inequalities and demeaning practices. The observed effects of inequality on security behaviours suggest that social disparities along the lines of income and social identity may quickly manifest in mistrust and segregation, eroding individuals' basic human rights. These social divisions can jeopardize commitments to practices that could improve long-term collective welfare, including environmental protection, international collaboration, and civic engagement. Understanding how and when people seek security may be instrumental in explaining how social fissures can develop, become entrenched, and perhaps be alleviated.

Another noteworthy consideration is how individuals in marginalized groups pursue their own security. Individuals in marginalized groups are far more likely to find themselves in dangerous areas partly because they have less money to spend on security. Correspondingly, marginalized groups may be more likely to seek out alternative security solutions. They might instead restrict their activities (e.g., not going out after dark), become more vigilant (e.g., developing insomnia), or coming to rely on local gangs. Although marginalized groups may prove to be absent from much of the security market, they are likely still incurring substantial costs to ensure their safety. Understanding these security practices may help to further explain how financial, social, and health risk factors can compound a constellation of vulnerability.

<!-- The next few hundred years may be disproportionately affected by the fortunes of African countries. In addition to their colonial histories, varied ethnic and religious groups, vulnerability to climate change, prevalence of poverty, and rich natural resources, these countries are among the fastest-growing. By 2100, the population in Africa is expected to quadruple from one billion to four billion people. In the meantime, population growth everywhere else has been slowing; in Asia, the most populated region in the world the population will only increase from four billion to five billion @worldometer2022 . These fast-growing countries are also among the most unequal in the world, meaning that over the next 100 years, most people will be born into high-inequality environments. -->

<!-- In addition to the subsequently high rates of poverty and absolute deprivation, these high-inequality countries may also foster populations with extremely high relative deprivation. The bourgening population will also mean increased investment from foreign markets, whether attempting to secure cheap labour forces, or service growing demand across the region (e.g., China's Belt and Road Initiative; G7's Build Back Better World Partnership). In a fast-moving, high-stakes, and competitive region, individuals in these countries may be acutely aware of how another's gain may be their loss. If the envy anticipation hypothesis holds, then these areas may turn out to be incredibly lucrative markets for the security industry to target and develop. -->

<!-- Conversely, if inequality is indeed-trust eroding, high-inequality regions may encounter substantial internal tensions and breakdowns in cooperation when faced with collective action problems. -->

<!-- social comparisons - comparison target selected is the higher-up individual -->

If someone locks their doors to their neighbors, should they be commended for their prudence or ridiculed for their suspicion? A normative prescription for how much security people should consume is unclear; the "right" amount of security consumption can vary both within and across individuals and circumstances (e.g., a rich vs. poor person purchasing security, or weighing the "ultimate price" of dying). The security industry provides a compelling intersection of social behaviour and expanding markets. This lens reveals numerous research questions that may help uncover the etiology of security consumption, such as the roles of household wealth, individual vulnerability, cultural norms, trust in police, personality traits, prejudice, and the consumption of fear-inducing news. This project has demonstrated that security behaviours are a useful window for examining how inequality strains trust. When the gap between winners and losers is large, individuals are more likely to expect envy, hostility, and risk-proneness from their partners. Given the ubiquity of inequality across societies and organizations, and the stakes of social trust for individual and collective well-being, the impacts of stratification on individuals' pursuit of security should not be ignored.

<!-- ### Competitive ability -->

<!-- ### Study 1b: Inequality in competitive standing (with real payoffs) -->

<!-- Study 1a is heavily based on a comparison-based extension of risk-sensitivity theory, namely that social comparisons with better-off others make individuals "move the goal-posts" towards more ambitious expectations, eliciting envy and dissatisfaction. One further extension of risk-sensitivity theory is in the relative state model @mishra2017, which posits that both environmental and embodied factors interact with social landscapes to yield a subjective evaluation of overall (dis)advantage. Individuals who have superior resources to bear (e.g., physical ability, money, social contacts) increases the expected value of certain risky activities (e.g., rock climbing), but not others (investment banking), so they engage in domain-specific risk-taking. By contrast, those with disadvantaged relative state (i.e., in a state of need), are more likely to take risks in many areas (e.g., gambling, lying) because their insufficient capital (e.g., money) leaves them unable to effectively reach their goals. -->

<!-- This relative (dis)advantage becomes especially consequential when individuals need to compete for contested resources. Individuals who are advantaged are more likely to win these contests, and have these victories snowball into greater advantage. For instance, an individual with greater intelligence would be more likely to be selected for a desirable job [@ceci1997], with the position leading to experiences, social contacts, and funds that they could leverage into any number of desirable outcomes (mates, prestigious schools). Accordingly. individuals who are immediately worse-off are likely to be disadvantaged for later contests, and will be in a 'state of need,' unable to reach their goals through low-risk alternatives. @mishra2014 found that participants took more risks when they received manipulated feedback on a test suggesting they had below-average intelligence. -->

<!-- <!--# seeks to explain observations that many risk-taking behaviours co-occur within individuals (i.e., risk-taking's domain-generality). The relative state model -->
